services:
  needapp-fe:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_GOOGLE_CLIENT_ID: ${NEXT_PUBLIC_GOOGLE_CLIENT_ID}
    image: needapp-fe:latest
    container_name: needapp-fe
    ports:
      - "3000:3000"
    restart: unless-stopped
